import { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { RichTextContent } from '../components/RichTextEditor';
import { useAuth } from '../contexts/AuthContext';
import { createComment, deleteComment, deletePost, getBoardCategories, getComments, getPost, getPostLikeStatus, incrementPostView, reportComment, reportPost, togglePostLike, type BoardCategory, type CommunityComment, type Post } from '../services/communityService';
import './CommunityPage.css';

const REPORT_REASONS = ['게시판의 성격과 맞는 게시글이 아닙니다.', '혐오/차별적/생명경시/욕설 표현입니다.', '스팸홍보/도배입니다.', '불법정보를 포함하고 있습니다.', '음란물입니다.', '불쾌한 표현이 있습니다.'];

export function CommunityPostPage() {
  const { postId } = useParams(); const { user, userProfile } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [post, setPost] = useState<Post | null>(null); const [categories, setCategories] = useState<BoardCategory[]>([]); const [comments, setComments] = useState<CommunityComment[]>([]); const [comment, setComment] = useState(''); const [replyTo, setReplyTo] = useState<string | null>(null); const [replyText, setReplyText] = useState(''); const [liked, setLiked] = useState(false); const [error, setError] = useState(''); const [reportTarget, setReportTarget] = useState<{ type: 'post' | 'comment'; id: string } | null>(null); const [reportReason, setReportReason] = useState(REPORT_REASONS[0]); const [reportDetails, setReportDetails] = useState('');
  const scrollY = (location.state as { communityScrollY?: number } | null)?.communityScrollY ?? 0;
  const backToList = () => navigate('/community', { state: { communityScrollY: scrollY } });
  const loadComments = () => postId && getComments(postId).then(setComments).catch(() => setError('댓글을 불러오지 못했습니다.'));
  useEffect(() => { getBoardCategories().then(setCategories).catch(() => undefined); }, []);
  useEffect(() => { if (!postId) return; getPost(postId).then(value => { setPost(value); if (value) void incrementPostView(postId); }).catch(() => setError('게시글을 불러오지 못했습니다.')); void getPostLikeStatus(postId).then(value => setLiked(value.liked)).catch(() => undefined); loadComments(); }, [postId]);
  const requireWriter = () => { if (!user) { navigate('/login'); return false; } if (!userProfile?.nickname) { navigate('/profile?setup=nickname&reason=write'); return false; } return true; };
  const submitComment = async (event: React.FormEvent, parentId: string | null = null) => { event.preventDefault(); const value = parentId ? replyText : comment; if (!postId || !value.trim() || !requireWriter()) return; try { await createComment(postId, value, parentId); if (parentId) { setReplyText(''); setReplyTo(null); } else setComment(''); loadComments(); setPost(current => current ? { ...current, comment_count: current.comment_count + 1 } : current); } catch { setError('댓글을 저장하지 못했습니다.'); } };
  const removeComment = async (id: string) => { if (!window.confirm('댓글 또는 답글을 삭제할까요?')) return; try { await deleteComment(id); loadComments(); } catch { setError('작성자 또는 관리자만 삭제할 수 있습니다.'); } };
  const remove = async () => { if (!postId || !window.confirm('이 게시글을 삭제할까요?')) return; try { await deletePost(postId); backToList(); } catch { setError('작성자 또는 관리자만 게시글을 삭제할 수 있습니다.'); } };
  const toggleLike = async () => { if (!postId) return; if (!user) { navigate('/login'); return; } try { const value = await togglePostLike(postId); setLiked(value.liked); setPost(current => current ? { ...current, like_count: value.like_count } : current); } catch { setError('좋아요를 저장하지 못했습니다.'); } };
  const share = async () => { try { if (navigator.share) await navigator.share({ title: post?.title || 'HOKEX 커뮤니티', url: window.location.href }); else { await navigator.clipboard.writeText(window.location.href); alert('게시글 링크를 복사했습니다.'); } } catch { /* 공유 취소 */ } };
  const submitReport = async (event: React.FormEvent) => { event.preventDefault(); if (!reportTarget) return; if (!user) { navigate('/login'); return; } try { if (reportTarget.type === 'post') await reportPost(reportTarget.id, reportReason, reportDetails); else await reportComment(reportTarget.id, reportReason, reportDetails); setReportTarget(null); setReportDetails(''); alert('신고가 접수되었습니다.'); } catch { setError('신고를 접수하지 못했습니다.'); } };
  const roots = comments.filter(item => !item.parent_comment_id); const replies = (id: string) => comments.filter(item => item.parent_comment_id === id); const boardName = categories.find(item => item.id === post?.board_category_id)?.name || '커뮤니티'; const canEdit = post?.author_id === user?.id; const canDelete = Boolean(canEdit || userProfile?.is_admin);
  const reportForm = reportTarget && <form className="report-form" onSubmit={submitReport}><h3>{reportTarget.type === 'comment' ? '댓글 신고' : '게시글 신고'}</h3><label>신고 사유<select value={reportReason} onChange={e => setReportReason(e.target.value)}>{REPORT_REASONS.map(reason => <option key={reason}>{reason}</option>)}</select></label><label>세부 내용<textarea value={reportDetails} onChange={e => setReportDetails(e.target.value)} maxLength={2000} placeholder="신고 사유를 구체적으로 작성해 주세요. (선택)" /></label><div><button type="button" onClick={() => setReportTarget(null)}>취소</button><button type="submit">신고 접수</button></div></form>;
  const commentItem = (item: CommunityComment, isReply = false) => <div className={`comment-item${isReply ? ' comment-reply' : ''}`} key={item.id}><strong>{item.author_nickname}</strong><time>{new Date(item.created_at).toLocaleString('ko-KR')}</time><p>{item.content}</p><div className="comment-actions"><button onClick={() => setReportTarget({ type: 'comment', id: item.id })}>신고</button>{!isReply && <button onClick={() => { if (requireWriter()) setReplyTo(replyTo === item.id ? null : item.id); }}>답글</button>}{(item.author_id === user?.id || userProfile?.is_admin) && <button onClick={() => removeComment(item.id)}>삭제</button>}</div>{reportTarget?.type === 'comment' && reportTarget.id === item.id && reportForm}{!isReply && replyTo === item.id && <form className="reply-form" onSubmit={e => submitComment(e, item.id)}><textarea value={replyText} onChange={e => setReplyText(e.target.value)} maxLength={2000} placeholder={`${item.author_nickname}님에게 답글 작성`} /><button type="submit">답글 등록</button></form>}{!isReply && replies(item.id).map(reply => commentItem(reply, true))}</div>;
  return <main className="community-page community-detail-page"><div className="community-layout"><aside className="community-sidebar"><strong>게시판</strong><button onClick={backToList}>전체 글</button>{categories.map(item => item.is_active ? <button key={item.id} className={post?.board_category_id === item.id ? 'active' : ''} onClick={backToList}>{item.icon} {item.name}</button> : <div key={item.id} className="community-category-heading">{item.icon} {item.name}</div>)}</aside><section className="community-content">{error && <div className="community-error">{error}</div>}{!post ? <div className="community-empty">게시글을 불러오는 중입니다.</div> : <article className="post-detail community-post-inline"><button className="back-link button-link" onClick={backToList}>← 커뮤니티 목록</button><div className="community-board-title"><p>HOKEX COMMUNITY</p><h2>{boardName}</h2></div><div className="post-detail-title"><span className="post-tag">COMMUNITY · 글번호 {post.post_number}{!post.is_public && ' · 비공개'}</span><h2>{post.title}</h2><p>{post.author_nickname || '익명 판다'} · {new Date(post.created_at).toLocaleString('ko-KR')} · 조회 {post.view_count}</p></div>{post.link_url && <a className="post-link-card" href={post.link_url}>🔗 연결된 링크 열기 <span>{post.link_url}</span></a>}<div className="post-detail-content"><RichTextContent value={post.content} /></div><div className="post-reactions"><button className={liked ? 'active' : ''} onClick={toggleLike}>♥ 좋아요 <b>{post.like_count}</b></button><button onClick={share}>↗ 공유</button><button onClick={() => setReportTarget({ type: 'post', id: post.id })}>⚑ 신고</button></div>{reportTarget?.type === 'post' && reportForm}{(canEdit || canDelete) && <div className="post-owner-actions">{canEdit && <button onClick={() => navigate(`/community/${post.id}/edit`)}>수정</button>}{canDelete && <button className="danger" onClick={remove}>삭제</button>}</div>}<section className="comments-section"><h3>댓글 <b>{comments.length}</b></h3>{roots.map(item => commentItem(item))}{!user ? <button className="comment-login-button" onClick={() => navigate('/login')}>로그인 후 댓글을 작성할 수 있습니다.</button> : !userProfile?.nickname ? <button className="comment-login-button" onClick={() => navigate('/profile?setup=nickname&reason=write')}>닉네임 설정 후 댓글을 작성할 수 있습니다.</button> : <form className="comment-form" onSubmit={e => submitComment(e)}><textarea value={comment} onChange={e => setComment(e.target.value)} maxLength={2000} placeholder="댓글을 작성해 주세요." /><button type="submit">등록</button></form>}</section></article>}</section></div></main>;
}
