import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import '../styles/LoginPage.css';

export function LoginPage() {
  const { user, loading, signInWithPassword, signInWithMagicLink, signUp, resetPassword } = useAuth();
  const navigate = useNavigate();
  const [mode, setMode] = useState<'login' | 'signup'>('login');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [passwordConfirm, setPasswordConfirm] = useState('');
  const [agreedToTerms, setAgreedToTerms] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (!loading && user) navigate('/'); }, [user, loading, navigate]);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setError(''); setNotice('');
    if (mode === 'signup') { if (!agreedToTerms) { setError('이용약관 및 개인정보처리방침에 동의해주세요.'); return; } if (password.length < 8) { setError('비밀번호는 8자 이상으로 입력해주세요.'); return; } if (password !== passwordConfirm) { setError('비밀번호 확인이 일치하지 않습니다.'); return; } }
    setSubmitting(true); try { if (mode === 'signup') { await signUp(email, password); setNotice('가입 확인 메일을 보냈습니다. 메일의 인증 링크를 누른 뒤 로그인해주세요.'); setMode('login'); setPassword(''); setPasswordConfirm(''); } else { sessionStorage.setItem('hokex-open-nickname-setup', 'true'); await signInWithPassword(email, password); } } catch (caught: unknown) { sessionStorage.removeItem('hokex-open-nickname-setup'); const message = caught instanceof Error ? caught.message : ''; if (message.includes('already registered')) setError('이미 가입된 이메일입니다. 로그인하거나 비밀번호를 재설정해주세요.'); else if (message.includes('Invalid login credentials')) setError('이메일 또는 비밀번호가 올바르지 않습니다.'); else setError(mode === 'signup' ? '가입에 실패했습니다. 잠시 후 다시 시도해주세요.' : '로그인에 실패했습니다. 다시 시도해주세요.'); } finally { setSubmitting(false); }
  };
  const sendMagicLink = async () => { if (!email.trim()) { setError('이메일 주소를 먼저 입력해주세요.'); return; } setSubmitting(true); setError(''); setNotice(''); try { sessionStorage.setItem('hokex-open-nickname-setup', 'true'); await signInWithMagicLink(email); setNotice('이메일로 로그인 링크를 보냈습니다. 메일함과 스팸함을 확인해주세요.'); } catch { sessionStorage.removeItem('hokex-open-nickname-setup'); setError('로그인 링크를 보내지 못했습니다. 잠시 후 다시 시도해주세요.'); } finally { setSubmitting(false); } };
  const forgotPassword = async () => { if (!email.trim()) { setError('비밀번호를 재설정할 이메일 주소를 먼저 입력해주세요.'); return; } setSubmitting(true); setError(''); setNotice(''); try { await resetPassword(email); setNotice('비밀번호 재설정 링크를 이메일로 보냈습니다.'); } catch { setError('재설정 링크를 보내지 못했습니다. 잠시 후 다시 시도해주세요.'); } finally { setSubmitting(false); } };
  if (loading) return <div className="login-container"><div className="login-box"><p>로딩 중...</p></div></div>;
  return <div className="login-container"><div className="login-box"><div className="login-header"><h1>HOKEX</h1><p>전국 전시·컨벤션 정보 플랫폼</p></div><div className="login-content"><div className="auth-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => { setMode('login'); setError(''); }}>로그인</button><button className={mode === 'signup' ? 'active' : ''} onClick={() => { setMode('signup'); setError(''); }}>회원가입</button></div><h2>{mode === 'signup' ? '호켁스 회원가입' : '로그인'}</h2><p className="login-description">행사와 커뮤니티는 누구나 볼 수 있으며, 글 작성과 저장 기능은 호켁스 회원에게 제공됩니다.</p><form onSubmit={submit} className="login-form"><div className="form-group"><label htmlFor="email">이메일</label><input type="email" id="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="name@example.com" required disabled={submitting} /></div><div className="form-group"><label htmlFor="password">비밀번호</label><input type="password" id="password" value={password} onChange={event => setPassword(event.target.value)} placeholder={mode === 'signup' ? '8자 이상 입력' : '비밀번호'} required disabled={submitting} />{mode === 'login' && <button type="button" className="forgot-password-link" onClick={forgotPassword} disabled={submitting}>비밀번호 찾기</button>}</div>{mode === 'signup' && <><div className="form-group"><label htmlFor="password-confirm">비밀번호 확인</label><input type="password" id="password-confirm" value={passwordConfirm} onChange={event => setPasswordConfirm(event.target.value)} placeholder="비밀번호를 다시 입력" required disabled={submitting} /></div><div className="terms-agreement"><label className="checkbox-label"><input type="checkbox" checked={agreedToTerms} onChange={event => setAgreedToTerms(event.target.checked)} disabled={submitting} /><span><a href="/terms.html" target="_blank" rel="noreferrer">이용약관</a> 및 <a href="/privacy.html" target="_blank" rel="noreferrer">개인정보처리방침</a>에 동의합니다.</span></label></div></>}{error && <div className="error-message">{error}</div>}{notice && <div className="success-message">{notice}</div>}<button className="login-btn primary-btn" disabled={submitting}>{submitting ? '처리 중…' : mode === 'signup' ? '가입하기' : '로그인'}</button></form>{mode === 'login' && <button type="button" className="login-btn secondary-btn" onClick={sendMagicLink} disabled={submitting}>✉️ 이메일 링크로 로그인</button>}<div className="newsletter-callout"><strong>카페인판다 뉴스레터</strong><p>호켁스 가입과 별개로, 업계 소식과 업데이트를 받아보세요.</p><a href="https://page.stibee.com/subscriptions/289942" target="_blank" rel="noreferrer">뉴스레터 구독하기</a></div></div></div></div>;
}
